sudo: required
dist: xenial
services:
  - docker
cache:
  directories:
    - ./htmltest/tmp

addons:
  snaps:
    - yq

before_install:
  # update gcloud apt source
  - bash ./themes/pxdocs-tooling/build/before_install.sh

script:
  # make the build fail if there are any errors
  - set -e
  - bash ./themes/pxdocs-tooling/build/build.sh

notifications:
  email:
    recipients:
      - harsh@portworx.com
    on_success: change
    on_failure: always